<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="acc_body_length" value="0.157" />
    <xacro:property name="ext_length" value="0.150" />

    <xacro:macro name="turning_mech" params="base">

        <link name="acc_1_ext">
            <inertial>
            <mass value="0.3"/>
            <origin xyz="0 0 ${ext_length}"/>
            <inertia ixx="0.005" iyy="0.005" izz="0.005" ixy="0" ixz="0" iyz="0"/>
            </inertial>
            <visual>
            <geometry>
                <cylinder radius="0.0075" length="${ext_length}"/>
            </geometry>
            </visual>
            <collision>
            <geometry>
                <cylinder radius="0.0075" length="${ext_length}"/>
            </geometry>
            </collision>
        </link>

        <link name="acc_1_body">
            <inertial>
            <mass value="0.5"/>
            <origin xyz="0 0 -${acc_body_length/2}"/>
            <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
            </inertial>
            <visual>
            <geometry>
                <box size="0.022 0.022 ${acc_body_length}"/>
            </geometry>
            </visual>
            <collision>
            <geometry>
                <box size="0.022 0.022 ${acc_body_length}"/>
            </geometry>
            </collision>
        </link>

        <link name="motor">
            <visual>
            <geometry>
                <cylinder radius="0.025" length="0.025"/> <!-- Motor cylinder -->
            </geometry>
            <origin rpy="0 1.5707 0"/> <!-- Rotate 90 degrees around Y-axis -->
            </visual>
            <collision>
            <geometry>
                <cylinder radius="0.025" length="0.025"/>
            </geometry>
            <origin rpy="0 1.5707 0"/> <!-- Rotate 90 degrees around Y-axis -->
            </collision>
        </link>

        <link name="acc_2_ext">
            <inertial>
            <mass value="0.3"/>
            <origin xyz="0 0 ${ext_length}"/>
            <inertia ixx="0.005" iyy="0.005" izz="0.005" ixy="0" ixz="0" iyz="0"/>
            </inertial>
            <visual>
            <geometry>
                <cylinder radius="0.0075" length="${ext_length}"/>
            </geometry>
            </visual>
            <collision>
            <geometry>
                <cylinder radius="0.0075" length="${ext_length}"/>
            </geometry>
            </collision>
        </link>

        <link name="acc_2_body">
            <inertial>
            <mass value="0.5"/>
            <origin xyz="0 0 ${acc_body_length/2}"/>
            <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
            </inertial>
            <visual>
            <geometry>
                <box size="0.022 0.022 ${acc_body_length}"/>
            </geometry>
            </visual>
            <collision>
            <geometry>
                <box size="0.022 0.022 ${acc_body_length}"/>
            </geometry>
            </collision>
        </link>

        <joint name="base_acc_1" type="fixed">
            <parent link="${base}"/>
            <child link="acc_1_body"/>
            <origin xyz="0 0 0"/>
        </joint>

        <joint name="acc_1" type="prismatic">
            <parent link="acc_1_body"/>
            <child link="acc_1_ext"/>
            <origin xyz="0 0 ${ext_length - acc_body_length}"/>
            <axis xyz="0 0 1"/>
            <limit lower="0" upper="${ext_length}" effort="100.0" velocity="1.0"/>
        </joint>

        <joint name="acc_1_motor" type="revolute">
            <parent link="acc_1_ext"/>
            <child link="motor"/>
            <origin xyz="0 0 ${ext_length/2+0.025}"/>
            <limit lower="-2.356" upper="2.356" effort="50.0" velocity="3.0"/> <!-- Â±135 degrees -->
        </joint>

        <joint name="motor_acc_2" type="fixed">
            <parent link="motor"/>
            <child link="acc_2_ext"/>
            <origin xyz="0 0 ${ext_length/2+0.025}"/>
        </joint>

        <joint name="acc_2" type="prismatic">
            <parent link="acc_2_ext"/>
            <child link="acc_2_body"/>
            <origin xyz="0 0 ${ext_length - acc_body_length}"/>
            <axis xyz="0 0 1"/>
            <limit lower="0" upper="${ext_length}" effort="100.0" velocity="1.0"/>
        </joint>

    </xacro:macro>

</robot>